import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import Providers from "./providers";
import AuthModal from "../components/ui/AuthModal";
import AuthListener from "../components/auth/AuthListener";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthListener />
          <Navbar />
          <AuthModal />
          {children}
        </Providers>
      </body>
    </html>
  );
}
